require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpoApplicantsController do

  # This should return the minimal set of attributes required to create a valid
  # IpoApplicant. As you add validations to IpoApplicant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "production" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpoApplicantsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipo_applicants as @ipo_applicants" do
      ipo_applicant = IpoApplicant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipo_applicants).should eq([ipo_applicant])
    end
  end

  describe "GET show" do
    it "assigns the requested ipo_applicant as @ipo_applicant" do
      ipo_applicant = IpoApplicant.create! valid_attributes
      get :show, {:id => ipo_applicant.to_param}, valid_session
      assigns(:ipo_applicant).should eq(ipo_applicant)
    end
  end

  describe "GET new" do
    it "assigns a new ipo_applicant as @ipo_applicant" do
      get :new, {}, valid_session
      assigns(:ipo_applicant).should be_a_new(IpoApplicant)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipo_applicant as @ipo_applicant" do
      ipo_applicant = IpoApplicant.create! valid_attributes
      get :edit, {:id => ipo_applicant.to_param}, valid_session
      assigns(:ipo_applicant).should eq(ipo_applicant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpoApplicant" do
        expect {
          post :create, {:ipo_applicant => valid_attributes}, valid_session
        }.to change(IpoApplicant, :count).by(1)
      end

      it "assigns a newly created ipo_applicant as @ipo_applicant" do
        post :create, {:ipo_applicant => valid_attributes}, valid_session
        assigns(:ipo_applicant).should be_a(IpoApplicant)
        assigns(:ipo_applicant).should be_persisted
      end

      it "redirects to the created ipo_applicant" do
        post :create, {:ipo_applicant => valid_attributes}, valid_session
        response.should redirect_to(IpoApplicant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipo_applicant as @ipo_applicant" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpoApplicant.any_instance.stub(:save).and_return(false)
        post :create, {:ipo_applicant => { "production" => "invalid value" }}, valid_session
        assigns(:ipo_applicant).should be_a_new(IpoApplicant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpoApplicant.any_instance.stub(:save).and_return(false)
        post :create, {:ipo_applicant => { "production" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipo_applicant" do
        ipo_applicant = IpoApplicant.create! valid_attributes
        # Assuming there are no other ipo_applicants in the database, this
        # specifies that the IpoApplicant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpoApplicant.any_instance.should_receive(:update).with({ "production" => "MyString" })
        put :update, {:id => ipo_applicant.to_param, :ipo_applicant => { "production" => "MyString" }}, valid_session
      end

      it "assigns the requested ipo_applicant as @ipo_applicant" do
        ipo_applicant = IpoApplicant.create! valid_attributes
        put :update, {:id => ipo_applicant.to_param, :ipo_applicant => valid_attributes}, valid_session
        assigns(:ipo_applicant).should eq(ipo_applicant)
      end

      it "redirects to the ipo_applicant" do
        ipo_applicant = IpoApplicant.create! valid_attributes
        put :update, {:id => ipo_applicant.to_param, :ipo_applicant => valid_attributes}, valid_session
        response.should redirect_to(ipo_applicant)
      end
    end

    describe "with invalid params" do
      it "assigns the ipo_applicant as @ipo_applicant" do
        ipo_applicant = IpoApplicant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpoApplicant.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipo_applicant.to_param, :ipo_applicant => { "production" => "invalid value" }}, valid_session
        assigns(:ipo_applicant).should eq(ipo_applicant)
      end

      it "re-renders the 'edit' template" do
        ipo_applicant = IpoApplicant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpoApplicant.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipo_applicant.to_param, :ipo_applicant => { "production" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipo_applicant" do
      ipo_applicant = IpoApplicant.create! valid_attributes
      expect {
        delete :destroy, {:id => ipo_applicant.to_param}, valid_session
      }.to change(IpoApplicant, :count).by(-1)
    end

    it "redirects to the ipo_applicants list" do
      ipo_applicant = IpoApplicant.create! valid_attributes
      delete :destroy, {:id => ipo_applicant.to_param}, valid_session
      response.should redirect_to(ipo_applicants_url)
    end
  end

end
