require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IposController do

  # This should return the minimal set of attributes required to create a valid
  # Ipo. As you add validations to Ipo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "pre_ipo_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IposController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipos as @ipos" do
      ipo = Ipo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipos).should eq([ipo])
    end
  end

  describe "GET show" do
    it "assigns the requested ipo as @ipo" do
      ipo = Ipo.create! valid_attributes
      get :show, {:id => ipo.to_param}, valid_session
      assigns(:ipo).should eq(ipo)
    end
  end

  describe "GET new" do
    it "assigns a new ipo as @ipo" do
      get :new, {}, valid_session
      assigns(:ipo).should be_a_new(Ipo)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipo as @ipo" do
      ipo = Ipo.create! valid_attributes
      get :edit, {:id => ipo.to_param}, valid_session
      assigns(:ipo).should eq(ipo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ipo" do
        expect {
          post :create, {:ipo => valid_attributes}, valid_session
        }.to change(Ipo, :count).by(1)
      end

      it "assigns a newly created ipo as @ipo" do
        post :create, {:ipo => valid_attributes}, valid_session
        assigns(:ipo).should be_a(Ipo)
        assigns(:ipo).should be_persisted
      end

      it "redirects to the created ipo" do
        post :create, {:ipo => valid_attributes}, valid_session
        response.should redirect_to(Ipo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipo as @ipo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ipo.any_instance.stub(:save).and_return(false)
        post :create, {:ipo => { "pre_ipo_id" => "invalid value" }}, valid_session
        assigns(:ipo).should be_a_new(Ipo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ipo.any_instance.stub(:save).and_return(false)
        post :create, {:ipo => { "pre_ipo_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipo" do
        ipo = Ipo.create! valid_attributes
        # Assuming there are no other ipos in the database, this
        # specifies that the Ipo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ipo.any_instance.should_receive(:update).with({ "pre_ipo_id" => "1" })
        put :update, {:id => ipo.to_param, :ipo => { "pre_ipo_id" => "1" }}, valid_session
      end

      it "assigns the requested ipo as @ipo" do
        ipo = Ipo.create! valid_attributes
        put :update, {:id => ipo.to_param, :ipo => valid_attributes}, valid_session
        assigns(:ipo).should eq(ipo)
      end

      it "redirects to the ipo" do
        ipo = Ipo.create! valid_attributes
        put :update, {:id => ipo.to_param, :ipo => valid_attributes}, valid_session
        response.should redirect_to(ipo)
      end
    end

    describe "with invalid params" do
      it "assigns the ipo as @ipo" do
        ipo = Ipo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ipo.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipo.to_param, :ipo => { "pre_ipo_id" => "invalid value" }}, valid_session
        assigns(:ipo).should eq(ipo)
      end

      it "re-renders the 'edit' template" do
        ipo = Ipo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ipo.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipo.to_param, :ipo => { "pre_ipo_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipo" do
      ipo = Ipo.create! valid_attributes
      expect {
        delete :destroy, {:id => ipo.to_param}, valid_session
      }.to change(Ipo, :count).by(-1)
    end

    it "redirects to the ipos list" do
      ipo = Ipo.create! valid_attributes
      delete :destroy, {:id => ipo.to_param}, valid_session
      response.should redirect_to(ipos_url)
    end
  end

end
